[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bach-googleads"
description = "Manages tasks in Google Ads"
authors = [
  {name = "Google Inc. (gTech gPS CSE team)", email = "no-reply@google.com"},
  {name = "Andrei Markin", email = "amarkin@google.com"},
]
license = {text = "Apache 2.0"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "garf-google-ads",
  "croniter",
  "garf_executors",
  "garf_youtube",
  "pydantic",
  "typing-extensions",
  "typer",
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]
dynamic = ["version"]

[project.optional-dependencies]
persist = [
  "sqlalchemy>2",
]
server = [
  "fastapi[standard]",
]
test =  [
  "pytest",
  "pytest-cov",
  "pytest-mock",
]
all = [
  "bach[persist,server]"
]

[project.entry-points.bach_actors]
placement_performance = "bach.plugins.exclusions.placement_excluder"
search_term_performance = "bach.plugins.exclusions.keyword_excluder"
keyword_performance = "bach.plugins.exclusions.keyword_excluder"

[tool.pytest.ini_options]
testpaths = [
  "tests",
]

[project.scripts]
bach="bach.entrypoints.cli:typer_app"
bach-server="bach.entrypoints.server:typer_app"
